version: '3'
services:
    db:
        image: postgres
        ports:
            - 5432:5432
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${PASSWORD}
            - POSTGRES_DB=${DATABASE_NAME}
        volumes:
            - postgres-data:/var/lib/postgresql/data
    app:
        build: .
        volumes:
            - .:/home/app
        ports:
            - 3000:3000
        depends_on:
            - db
volumes:
    postgres-data:
