{{ range .Values.components }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name -}}-service
spec:
  selector:
    app: {{ .name -}}-app
  {{- if .nodePort}}
  type: LoadBalancer
  {{- end }}
  ports:
  - protocol: TCP
    port: {{ .containerPort }}
    targetPort: {{ .containerPort }}
    {{- if .nodePort}}
    nodePort: {{ .nodePort }}
    {{- end}}
{{- end }}
